version: "3.5"
x-default: &default
  restart: always
  logging:
    options:
      max-size: "5M"
      max-file: "5"
services:
  proxy:
    image: registry.cn-shenzhen.aliyuncs.com/juxuny-public/tcp-proxy:v1.0.2
    entrypoint: /app/entrypoint -l :20000 -r ${HOST_IP}:10000 --to-proxy-protocol --from-de-xun -t 10
    ports:
      - 20000:20000
    <<: *default
